### ISSUE TITLE
Dimensions of color surface does not match dimensions of depth surface

### ISSUE THREAD

**Issue by benoneal** [SlightlyMad/VolumetricLights#1]
I'm getting this error every frame: 
```Dimensions of color surface does not match dimensions of depth surface
UnityEditor.DockArea:OnGUI()```
(also this plugin is amazing. Seriously incredible results)

**Comment by grofie** [comment]
Getting the same error when using full resolution, with half or less the the error is gone.

But seriously, really great plugin, amazing work, totally impressed! Thanks allot!

We also got the problem that the plugin stops working when switching windows. I changed this in the renderer script to fix the issue:

 `   void OnEnable()
    {
  //      _camera.RemoveAllCommandBuffers();
        _camera.AddCommandBuffer(CameraEvent.BeforeLighting, _preLightPass);
        _camera.AddCommandBuffer(CameraEvent.AfterLighting, _postLightPass);
        _camera.AddCommandBuffer(CameraEvent.BeforeFinalPass, _preFinalPass);
    }

    void OnDisable()
    {
    //    _camera.RemoveAllCommandBuffers();
        _camera.RemoveCommandBuffer(CameraEvent.BeforeLighting, _preLightPass);
        _camera.RemoveCommandBuffer(CameraEvent.AfterLighting, _postLightPass);
        _camera.RemoveCommandBuffer(CameraEvent.BeforeFinalPass, _preFinalPass);
    }
`

**Comment by SlightlyMad** [comment]
I'll look into it. Use Half resolution if you can. It is better for performance anyway.

@grofie Thanks for the fix. I'll "merge it" to the master.

And thank you guys for the positive feedback!

**Comment by SlightlyMad** [comment]
fixed
