### ISSUE TITLE
Multiple cameras

### ISSUE THREAD

**Issue by wisien92** [SlightlyMad/VolumetricLights#10]
Hi,

I have been using this Unity extention and it's great! But I came across one problem. To avoid gun clipping I have added second camera that draws only player and gun.

So my main camera has depth -1, and my gun camera has depth 1. With that I cannot see cone or any lightning effects. I alo can't add renderrer script to gun camera since it does not render walls.

Is there a way to bypass this problem or should I try different way to fix gun clipping?

**Comment by SlightlyMad** [comment]
This old trick with second camera doesn't work well with most modern rendering techniques (hdr, deferred rendering, post process effects, etc.). I think it is best just to avoid using second camera. There's a bunch of techniques how you can prevent gun clipping with only one camera (custom projection, gun scaling, clearing z-buffer for the gun only...). I suggest to explore those instead.

**Comment by wisien92** [comment]
Ok - thanks for tips!
