### ISSUE TITLE
Transparency issues - are they just renderque or more fundamental?

### ISSUE THREAD

**Issue by JamFKS** [SlightlyMad/VolumetricLights#11]
Playing with this volumetric lighting in a project of ours - looks absolutely brilliant, except of course for transparent geometry which looks like it's being rendered later. Is it just a matter of twiddling the shaders' render queues (which I can't seem to do in unity with these compiled shaders), or is there something more fundamental going on?

You can see in this image the water (black bits) seems to be being rendered after the volumetric effect, which is a shame.

![volumetric](https://cloud.githubusercontent.com/assets/26869154/24604438/1295d3da-18a8-11e7-8d07-374eebb651fb.png)

**Comment by JamFKS** [comment]
Yes - if I change my river shader to 1999 it works properly, but of course that's not a transparent queue so the river shader itself doesn't look so hot.

Would it be possible to change your shader queues to 3001?

![volumetric-2](https://cloud.githubusercontent.com/assets/26869154/24606042/b148ff24-18ae-11e7-90c7-704db0c8f7fd.png)

**Comment by SlightlyMad** [comment]
I'm afraid that changing rendering order doesn't really solve the problem. The effect will be always computed for solid geometry only. That is a limitation of the technique.
You can apply it after transparent geometry if you want. Delete [ImageEffectOpaque] in VolumetricLightRenderer. It may look ok depending on your use case but it won't be correct.

**Comment by JamFKS** [comment]
Thanks - commenting out that tag resolved the draw order issue totally. It now looks perfect for our use case - thanks.
