### ISSUE TITLE
Is it not work in iOS?

### ISSUE THREAD

**Issue by LeandroFavero** [SlightlyMad/VolumetricLights#7]
I tried but received this message:

Invalid pass number (2) for Graphics.Blit (Material "Hidden/BilateralBlur" with 1 passes)
UnityEngine.Graphics:Blit(Texture, RenderTexture, Material, Int32)
VolumetricLightRenderer:OnRenderImage(RenderTexture, RenderTexture) (at Assets/Scripts/VolumetricLightRenderer.cs:337)

**Comment by Alx101** [comment]
I have not tried this in iOS. It also has not been updated and tested on the newest Unity version. I will look into it.

**Comment by SlightlyMad** [comment]
Mobile devices are not supported. Windows and Mac only (and potentially consoles but it is untested). I'll state it explicitly in readme next time I update it.
